In [1]:
true_labels = ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A','A', 'A', 'B', 'B', 'B','B', 'B', 'B', 'B', 'B', 'B', 'B']

In [2]:
predicted_labels = ['A', 'B', 'A', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B']

In [3]:
from sklearn.metrics import confusion_matrix

In [4]:
confusion_matrix(true_labels, predicted_labels)

array([[6, 4],
       [3, 7]])

In [5]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [6]:
precision_score(true_labels, predicted_labels, labels=['A', 'B'], pos_label='A')

0.6666666666666666

In [7]:
recall_score(true_labels, predicted_labels, labels=['A', 'B'] ,pos_label='A')

0.6

In [9]:
f1_score(true_labels, predicted_labels, labels=['A', 'B'], pos_label='A')

0.631578947368421

In [10]:
accuracy_score(true_labels, predicted_labels)

0.65

In [11]:
1 - accuracy_score(true_labels, predicted_labels)

0.35

In [12]:
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
x, y = np.arange(10).reshape((5, 2)), range(5)

In [18]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
y

range(0, 5)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.4, random_state=42)

In [23]:
x_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [25]:
y_train

[2, 0, 3]

In [26]:
x_test

array([[2, 3],
       [8, 9]])

In [27]:
y_test

[1, 4]