In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('buy-computer.csv')

In [10]:
df

age   income   student   credit   buy
0     1        3         2        1     0
1     1        3         2        2     0
2     2        3         2        1     1
3     3        2         2        1     1
4     3        1         1        1     1
5     3        1         1        2     0
6     2        1         1        2     1
7     1        2         2        1     0
8     1        1         1        1     1
9     3        2         1        1     1
10    1        2         1        2     1
11    2        2         2        2     1
12    2        3         1        1     1
13    3        2         2        2     0

In [13]:
# use first 4 attributes as training data
x = df[['age', 'income', 'student', 'credit']].to_numpy()

In [14]:
x

array([[1, 3, 2, 1],
       [1, 3, 2, 2],
       [2, 3, 2, 1],
       [3, 2, 2, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 2],
       [2, 1, 1, 2],
       [1, 2, 2, 1],
       [1, 1, 1, 1],
       [3, 2, 1, 1],
       [1, 2, 1, 2],
       [2, 2, 2, 2],
       [2, 3, 1, 1],
       [3, 2, 2, 2]])

In [15]:
x.shape

(14, 4)

In [ ]:
# class labels for decision data
y = df['buy'].to_numpy()

In [18]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
# train, construct & learn decision tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x, y)

In [21]:
# age <= 30, income = medium, student = yes, credit rating = fair
new_customer = [1, 2, 1, 1]


In [22]:
clf.predict([np.array(new_customer)])

array([1])

In [23]:
clf.predict(x)

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [24]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])