In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('movie_reviews.csv')

In [5]:
df

,text,label
0,It's been about 14 years since Sharon Stone aw...,0
1,someone needed to make a car payment... this i...,0
2,The Guidelines state that a comment must conta...,0
3,This movie is a muddled mish-mash of clichés f...,0
4,Before Stan Laurel became the smaller half of ...,0
...,...,...
4995,"Man, I loved this movie! This really takes me ...",1
4996,Recovery is an incredibly moving piece of work...,1
4997,"You can take the crook out of the joint, but i...",1
4998,FUTZ is the only show preserved from the exper...,1


In [6]:
df.columns

Index(['text', 'label'], dtype='object')

In [8]:
df.head(10)

,text,label
0,It's been about 14 years since Sharon Stone aw...,0
1,someone needed to make a car payment... this i...,0
2,The Guidelines state that a comment must conta...,0
3,This movie is a muddled mish-mash of clichés f...,0
4,Before Stan Laurel became the smaller half of ...,0
5,This is the best movie I've ever seen! <br /><...,1
6,The morbid Catholic writer Gerard Reve (Jeroen...,1
7,"""Semana Santa"" or ""Angel Of Death"" is a very w...",0
8,Somebody mastered the difficult task of mergin...,1
9,Why did I waste 1.5 hours of my life watching ...,0


In [ ]:
# sort so positive reviews are at top, negative are at bottom
df.sort_values(by = 'label', ascending= False, inplace= True)

In [14]:
df_positive_100 = df.head(100)

In [15]:
df_negative_100 = df.tail(100)

In [18]:
# convert text to list items
positive_100 = df_positive_100.iloc[:,0].to_list()
negative_100 = df_negative_100.iloc[:,0].to_list()

In [ ]:

positive_100[:10]

["This is the best movie I've ever seen! <br /><br />Maybe it's because I live just a few miles from the village were the story take place, and I know how things work out in this area in Sweden. The movie tells the truth, believe me! It both criticizes and honors the lifestyle of Dalarna, and the producer wants people who watch the movie to be more opened minded and care more for your closest friends and relatives.<br /><br />But if you live in another small village anywhere in Sweden (or another country) you will probably also recognize much from this movie.<br /><br />Thank you Maria Blom!",
 'The morbid Catholic writer Gerard Reve (Jeroen Krabbé) that is homosexual, alcoholic and has frequent visions of death is invited to give a lecture in the literature club of Vlissingen. While in the railway station in Amsterdam, he feels a non-corresponded attraction to a handsome man that embarks in another train. Gerard is introduced to the treasurer of the club and beautician Christine Halss

In [23]:
from nltk.corpus import stopwords
import string
english_stops = stopwords.words('english')

In [25]:
len(english_stops)

198

In [27]:
def my_clean_words(s):
    all_words = []
    review = s.translate(str.maketrans('','',string.punctuation))
    words = review.split()
    for w in words:
        w = w.lower()
        if w not in english_stops:
            all_words.append(w)
    return all_words

In [30]:
pos_100_words = []
pos_100_words_list = []

for review in positive_100:
    words_cleaned = my_clean_words(review)
    pos_100_words_list.append(words_cleaned)
    for word in words_cleaned:
        pos_100_words.append(word)

In [35]:
print(len(pos_100_words_list))
print(len(pos_100_words))
print(len(set(pos_100_words)))

100
13037
5141


In [36]:
neg_100_words = []
neg_100_words_list = []

for review in negative_100:
    words_cleaned = my_clean_words(review)
    neg_100_words_list.append(words_cleaned)
    for word in words_cleaned:
        neg_100_words.append(word)

In [38]:
print(len(neg_100_words_list))
print(len(neg_100_words))
print(len(set(neg_100_words)))

100
11804
4468


In [39]:
print(len(set(neg_100_words+pos_100_words)))

7762


In [40]:
attribute_words = list(set(neg_100_words + pos_100_words))

In [56]:
# transform pos reviews into one-hot encodings

pos_vectors = []

for i in range(len(pos_100_words_list)):
    vector = []
    for j in range(len(attribute_words)):
        if attribute_words[j] in pos_100_words_list[i]:
            vector.append(1)
        else:
            vector.append(0)
    pos_vectors.append(vector)

In [48]:
len(pos_vectors)

100

In [51]:
print(pos_vectors[0])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [57]:
# transform neg reviews into one-hot encodings

neg_vectors = []

for i in range(len(neg_100_words_list)):
    vector = []
    for j in range(len(attribute_words)):
        if attribute_words[j] in neg_100_words_list[i]:
            vector.append(1)
        else:
            vector.append(0)
    neg_vectors.append(vector)

In [58]:
len(neg_vectors)

100

In [60]:
len(neg_vectors[0])

7762

In [62]:
import numpy as np
x = np.array(pos_vectors + neg_vectors)

In [65]:
x.shape

(200, 7762)

In [67]:
pos_negative_labels = []
for i in range(100):
    pos_negative_labels.append(1)
for i in range(100):
    pos_negative_labels.append(0)

In [68]:
y = np.array(pos_negative_labels)

In [70]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state=42)
clf = clf.fit(x, y)

In [72]:
clf.predict(x[:10])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [76]:
clf.predict(x[-10:])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [79]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= .5, random_state= 42)

In [82]:
DT_model = tree.DecisionTreeClassifier(random_state=42)

In [84]:
DT_model = DT_model.fit(x_train, y_train)

In [85]:
y_train_pred = DT_model.predict(x_train)
y_test_pred = DT_model.predict(x_test)

In [87]:
y_test_pred

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [89]:
print(accuracy_score(y_true=y_train,y_pred=y_train_pred))

1.0


In [92]:
print(accuracy_score(y_true=y_test,y_pred=y_test_pred))

0.63


In [93]:
from sklearn.model_selection import cross_val_score

In [95]:
scores = cross_val_score(DT_model, x, y, cv = 2)

In [97]:
scores

array([0.56, 0.65])

In [98]:
print('CV Scores: ', scores)
print('Avg CV Score: ', scores.mean())
print('# of CV Scores used in Avg: ', len(scores))

CV Scores:  [0.56 0.65]
Avg CV Score:  0.605
# of CV Scores used in Avg:  2


In [100]:
print(cross_val_score(DT_model, x, y, cv = 5))

[0.65  0.6   0.725 0.55  0.575]
